### ISSUE TITLE
Error Localization?

### ISSUE THREAD

**Issue by Boscop** [Keats/validator#39]
When using a range or length validator I want to display the min and max args in the error but in a different language, how to do that?

**Comment by Keats** [comment]
You can pass a `message` attribute like `#[validate(range(min = "1", max = "2", message="La valeur doit etre entre %s et %s"))]`. The crate will not automatically interpolate the `min`/`max` variables though so you will have to do it yourself after validation or in the frontend

**Comment by Boscop** [comment]
Thanks, will the non-custom validators interpolate their values though?

**Comment by Keats** [comment]
1. code is a short code in case you want to translate in many languages and just settings a `message` won't be enough: you can lookup `email` in a translations dict for example for the current language

2. Nope, I'm just used to python: there is no interpolation at all in the crate so you can use `MIN_LENGTH`, `{}`, `====` or whatever you want

3. Sadly I don't think there is a good i18n crate right now so I would probably just do it manually for each error type since for example the `length` validator can have a min, a max or both. Hopefully there will be a good library like gettext to standardise to at some point

**Comment by Boscop** [comment]
What about this one? https://github.com/vitiral/strfmt
Apparently it doesn't support `{}` but `{foo}` syntax.

**Comment by Keats** [comment]
It seems ok but not good enough for localization where you have singular/plural

**Comment by Keats** [comment]
Closing this, I don't think it should be done as part of the crate. If you are using something like gettext/fluent, you can write a message with the right syntax and build it up afterwards.
