### ISSUE TITLE
Easy way to get a Vec<ValidationError>

### ISSUE THREAD

**Issue by jamessewell** [Keats/validator#80]
I'm using nested validations, and it would be great if there was a simple way to get at the ValidationError objects.

At the moment it's obscured by the many levels of ValidationErrors

**Comment by Keats** [comment]
How would that work? A `ValidationError` doesn't have the name of the field the error is on so you would get a bunch of errors but not know where it actually comes from.

**Comment by jamessewell** [comment]
True.

How about a human readable display for the whole thing?

**Comment by jamessewell** [comment]
Ok so thinking about this more I would really love something like what `serde_json` does:

```
Json deserialize error: unknown field `orthing`, expected `easting` or `northing` at line 1 column 365
```

But I suppose you need proper serde hooks to get line and column info.

Maybe something like:

```
Validate error: field `easting`, value 181 is not between -180 and +180
```

Sure it doesn't include any of the nesting information, but it's good enough for the majority of cases.

**Comment by incker** [comment]
You can get a field name, my code snipet:

        my_struct.validate().map_err(|err: ValidationErrors| {
            let errors: HashMap<&str, validator::ValidationErrorsKind> = err.into_errors();
            for (field, err) in errors {
                // do what you need
            }
        })

I it good thing if you will make own wrapper over validator

And by the way, @jamessewell, you can make custom message errors, like `#[validate(length(min = 1, max = 255, message = "your good readable error"))]`

+ close issue if I have answered all questions

**Comment by Keats** [comment]
Not all errors have a key. For example what would be the param key for a failed validation of the second string in a `vec` of a nested key? It could be an `Option` but it wouldn't be that great either since it would only be there in some cases.

**Comment by dyedgreen** [comment]
I was also running into this issue. It would really help in my case, if the error `Display` was more presentable, such that it could e.g. be echoed out directly to users. (Example use case would be returning this error from a GraphQL api, and just displaying the error on the client side.)

@Keats I was thinking about a format similar to this:

### Format individual errors
```rust
match (message, code) {
  (None, None) => /* some default format, e.g. value 181 is not between -180 and +180 */,
  (Some(msg), None) => msg.to_string(),
  (Some(msg), Some(code)) => format!("{} ({})", msg, code),
}
```

### Format `ValidationErrors` collection
- for each error on a field do `{field_name}: {error1}, {error2}, ..., {errorN}`
- for nested structs recursively do `{field_name}.{nested_errors}` (so that you get `nested.field.name: Some error here`)
- for arrays follow a similar strategy and do `{field_name}.[{index}].{nested_errors}`
- separate each error with `\n` (or `;`)

### The final display output should look something like this:
```
field: My error message (5)
nested.field: My other message
field.in.array.[2]: {default format here}
```

Would be happy to try and implement something like this if you're interested!

**Comment by Keats** [comment]
I'm ok having a better `Display` implementation but relying on it to display errors to end users would be bad imo. You want to co-locate the field error to the field, it's maddening otherwise.

**Comment by singulared** [comment]
Maybe it can be helpful for you:
https://github.com/rambler-digital-solutions/actix-web-validator/blob/master/src/error.rs#L65
