### ISSUE TITLE
Option<Vec<Struct>> doesn't work

### ISSUE THREAD

**Issue by jamessewell** [Keats/validator#83]
Looks like a `Vec<Struct>` works and an `Option<Struct>` works, but an `Option<Vec<Struct>>` does not.

```
error[E0599]: no method named `validate` found for type `&std::vec::Vec<model::executeAlert::LanguageContentMap>` in the current scope
  --> src/model/executeAlert.rs:49:41
   |
   | #[derive(Debug, Serialize, Deserialize, Validate)]
   |         
```

```rust
#[validate]
        languageContentMap: Option<Vec<LanguageContentMap>>,
```

This will build if I remove the `#[validate]`

**Comment by Keats** [comment]
Can you do a PR or paste a failing test?

**Comment by castarco** [comment]
In general it does not work on almost any nested data structure, this includes HashMaps, BTreeMaps, Vectors. I think the macros are not generating code for these cases, where the thing to be validated is precisely the items contained in the data structures.

**Comment by Keats** [comment]
It should not be too hard to add the code for that if someone wants to work on it

**Comment by Kaiser1989** [comment]
As long there is no fix, simple Workaround:
```
pub trait VecValidate {
    fn validate(&self) -> Result<(), ValidationErrors>;
}
impl<T: Validate> VecValidate for Vec<T> {
    fn validate(&self) -> Result<(), ValidationErrors> {
        for i in self.iter() { i.validate()? }
        Ok(())
    }
}
```
You just need to provide the trait to your scope, when using: Option<Vec<Anything>>.

**Comment by ssokolow** [comment]
@Kaiser1989 Thanks. `Vec` was working fine in my use case, but that was what I needed to adapt to get `HashMap<K, V: Validate>` working.

(Something I'm sure of, because my "Protect against the footgun of how easy it is to drop a `#[validate]` and not notice" regression tests get the validation errors they expect.)

...though I still don't understand how validator duck-types its way to accepting a `HashMapValidate` that I defined.
